### PR TITLE
Feature/library

### PR DESCRIPTION
**Pull request by aracelicaes**
TSE,
This is the Library Project for The Javascript Odin Curriculum. We are building Book Objects and pushing them into a myLibrary array. From there, we use the myLibrary array to display each book, and also to create the event handlers.

We are aware it's unfinished, we're just hoping we can get a little bit of confirmation that we're on the right track. 
Also, since local storage is optional, we have opted to not implement it yet. Therefore, when testing, please ensure you avoid refreshing the page to avoid deletion of all your created books. 

Thanks in advance,
Jenny and Ara

### CODE REVIEW

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @aracelicaes  & @janis-jenny**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [x] a lot of the sections in your readme file is really vague, you should make sure to add clear, detailed instructions on how to run the project locally. ( i.e. how to clone it, set it up, and run it)
- [x] your project has linter errors, please make sure to fix them before asking for another code review.
- [x] this project is about using js to create html elements dynamically with data that is imported from stored book object gathered in an array. after saying that, here is what the project is supposed to have:
1- a central array to store all book objects ✔️ 
2- a constructor function that is able to create book objects ✔️ 
3- a newBook button that when clicked displayes a form that has all the fields to create a book object ❌ 
4- a displayBook function that takes a book object and displayes it dynamically on the page ✔️ 
5- a addBookToLibrary function that takes the input of the user and creates a book object and adds it to the to array of books ❌ ( you must understand that you have to have 2 different functions to create a book object and to create a book html element )

- [x] make sure that you display the dummy books once the user loads the page and not after a new book is created. 

- [x] Ideally, the html index page should only have one element in it ( the root element ) and all of the other elements should be created dynamically ( with js ).

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by LamiaSristy** [comment]
> ### Changes required ♻️
> **Hello @aracelicaes & @janis-jenny**
> 
> Great job with the project so far it looks amazing, but there are still some changes to be made:
> 
> ### Requested 🔴
> * [ ]  a lot of the sections in your readme file is really vague, you should make sure to add clear, detailed instructions on how to run the project locally. ( i.e. how to clone it, set it up, and run it)
> * [ ]  your project has linter errors, please make sure to fix them before asking for another code review.
> * [ ]  this project is about using js to create html elements dynamically with data that is imported from stored book object gathered in an array. after saying that, here is what the project is supposed to have:
>   1- a central array to store all book objects ✔️
>   2- a constructor function that is able to create book objects ✔️
>   3- a newBook button that when clicked displayes a form that has all the fields to create a book object ❌
>   4- a displayBook function that takes a book object and displayes it dynamically on the page ✔️
>   5- a addBookToLibrary function that takes the input of the user and creates a book object and adds it to the to array of books ❌ ( you must understand that you have to have 2 different functions to create a book object and to create a book html element )
> * [ ]  make sure that you display the dummy books once the user loads the page and not after a new book is created.
> * [ ]  Ideally, the html index page should only have one element in it ( the root element ) and all of the other elements should be created dynamically ( with js ).
> 
> please make these changes and request another code review.
> 
> if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

## You need to add those required points.

**Review by LamiaSristy — CHANGES_REQUESTED** [review]
# Status: Change Required. ♻️

Hello, @aracelicaes and @janis-jenny.

## Please add the changes my colleague and previous TSE  said you to do.
Feel free to reach me on slack @lamiasristy 🙋

Keep up the spirit always. Happy Coding 💻

**Review by trekab — APPROVED** [review]
#### Approved! :tada: 
Well done working on all the suggested changes, team! :+1: Keep up the good work! There are some "nice to fix" (optional) issues I'd like you to work on before merging your PR though. These include:
- [ ] __[Optional]__ The `Uncaught TypeError: Cannot read property 'id' of undefined` that shows up at the start of the application with no books. (__Hint:__ You could create a default book. :thinking: )
- [ ] __[Optional]__ Add the `.vscode` folder to your `.gitignore` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Pull request merged**
